"""Generate docs/data_dictionary.md from the clean tables (table, columns, source, years, access date)."""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW, CLEAN, DOCS = ROOT / "data" / "raw", ROOT / "data" / "clean", ROOT / "docs"

TABLES = {
    "states": ("Canonical state table: code, names, DOSM file slug, region, land area, capital coordinates", "pipeline/states.py (areas: DOSM/JUPEM)", None),
    "visitors_state_year": ("Domestic visitors ('000) by state visited", "DOSM Domestic Tourism Survey 2025 & 2024, Table 9", "dosm/tourism_domestic_2025.xlsx"),
    "od_tourists": ("Overnight tourists ('000) by state of origin x state visited", "DOSM DTS 2025, 2024 (Table 10) and DTS by State 2023 (Jadual 10)", "dosm/tourism_domestic_2025.xlsx"),
    "national_key_stats": ("National key statistics: expenditure, visitors, trips, length of stay, spend per trip, tourists / excursionists", "DOSM DTS 2025, Tables 1-2", "dosm/tourism_domestic_2025.xlsx"),
    "state_key_stats": ("Receipts (RM m), visitors, trips, spend per visitor / trip, average length of stay by state", "DOSM DTS by State 2023, Jadual 1", "dosm/state/tourism_domestic_2023_johor.xlsx"),
    "state_detail": ("Tourist / excursionist split, same-day vs overnight receipts and trips, nights, transport mode %, accommodation type %, NAPIC hotels & rooms", "DOSM DTS by State 2023, Jadual 2-6, 11-12, 14-15", "dosm/state/tourism_domestic_2023_johor.xlsx"),
    "top_places_dosm": ("Top five destinations and districts per state", "DOSM DTS 2025 Tables 8A-8B; DTS by State 2023 Jadual 9", "dosm/tourism_domestic_2025.xlsx"),
    "population_state": ("Mid-year population ('000)", "data.gov.my population_state", "datagovmy/population_state.parquet"),
    "socioeconomic_state": ("Household income, poverty, basic amenities access (district mean), real GDP", "data.gov.my hh_income_state, hh_poverty_state, hh_access_amenities, gdp_state_real_supply", "datagovmy/hh_income_state.parquet"),
    "foreign_arrivals_soe": ("Foreign arrivals by state of entry (context only)", "data.gov.my arrivals_soe", "datagovmy/arrivals_soe.parquet"),
    "accommodation_year": ("Hotels, rooms, average occupancy rate, domestic / foreign hotel guests by state and year (MYS = national)", "Tourism Malaysia Paid Accommodation Survey (public Power BI)", "TM"),
    "accommodation_quarter": ("Occupancy rate and hotel guests by state and quarter", "Tourism Malaysia Paid Accommodation Survey (public Power BI)", "TM"),
    "osm_points": ("Attractions, nature, heritage, airports (IATA) and rail stations with coordinates, assigned to states", "OpenStreetMap via Overpass API", "OSM"),
    "state_panel": ("Analysis panel: one row per state per year with every derived measure used by the metrics", "All of the above (pipeline/build_panel.py)", None),
    "text_items": ("De-identified public travel text: passage / comment, state, URL, source type, date, language hint. No usernames.", "Exa API, YouTube Data API", None),
    "jomrasa_state": ("Experience Score (raw, shrunk, interval), sample size, emotion mix, access / amenity sentiment", "JomRasa (pipeline/text)", None),
    "jomrasa_topics": ("Topic sentiment per state with sample size (empirical-Bayes shrunk)", "JomRasa", None),
    "jomrasa_quotes": ("Representative short quotes with source links", "JomRasa", None),
    "guide_places_raw": ("Traveller-guide listings: see / do / eat / drink / buy, with description, opening hours, address and coordinates where given", "English Wikivoyage destination pages, CC BY-SA 4.0 (pipeline/guide/collect.py)", None),
    "guide_destinations_raw": ("Traveller-guide towns: state, source page and revision id, opening paragraph, food notes", "English Wikivoyage, CC BY-SA 4.0", None),
    "jomrasa_places": ("Place catalogue: place, state, coordinates (Nominatim), tags, sentiment, quote", "JomRasa + OpenStreetMap Nominatim", None),
}


def main() -> None:
    manifest = json.loads((RAW / "_manifest.json").read_text())
    tm = json.loads((RAW / "tourism_malaysia" / "_access.json").read_text())["accessed"]
    osm = json.loads((RAW / "osm" / "airports.json").read_text(encoding="utf8"))["_accessed"]
    out = ["# Data dictionary", "", "Generated by `python -m pipeline.data_dictionary` from `data/clean/`.", ""]
    for name, (desc, source, key) in TABLES.items():
        f = CLEAN / f"{name}.parquet"
        if not f.exists():
            continue
        df = pd.read_parquet(f)
        date = {"TM": tm, "OSM": osm}.get(key) or (manifest.get(key, {}).get("accessed") if key else "derived")
        years = f"{int(df.year.min())}-{int(df.year.max())}" if "year" in df and df.year.notna().any() else "-"
        out += [f"## `{name}`", "", desc, "", f"- **Source:** {source}", f"- **Years:** {years}  ·  **Rows:** {len(df):,}  ·  **Accessed:** {date}", "",
                "| column | type | example |", "|---|---|---|"]
        for c in df.columns:
            ex = df[c].dropna().iloc[0] if df[c].notna().any() else ""
            ex = f"{ex:.4g}" if isinstance(ex, float) else str(ex)[:60].replace("|", "/").replace("\n", " ")
            out.append(f"| `{c}` | {df[c].dtype} | {ex} |")
        out.append("")
    DOCS.mkdir(exist_ok=True)
    (DOCS / "data_dictionary.md").write_text("\n".join(out), encoding="utf8")
    print(f"docs/data_dictionary.md: {sum(1 for l in out if l.startswith('## '))} tables")


if __name__ == "__main__":
    main()
